spring.datasource.url: jdbc:mysql://papatoza.beget.tech:3306/papatoza_se?allowPublicKeyRetrieval=true&amp&useSSL=false&amp&serverTimezone=UTC
spring.datasource.username: papatoza_se
spring.datasource.password: 5OABCu40
spring.batch.jdbc.table-prefix: search_engine
spring.jpa.hibernate.ddl-auto: none
spring.jpa.properties.hibernate.jdbc.batch_size: 5
spring.jpa.properties.hibernate.order_inserts: true

server.port: ${PORT:8080}
spring.liquibase.enabled: true

url.default: /admin


useragent.name: searchBot/0.1

siteconfig:
  sites:
    - url: https://vz.ru
      name: Газета Взгляд
    - url: https://smi2.ru
      name: smi2
    - url: https://tass.ru
      name: ТАСС
    - url: https://iz.ru/
      name: Известия




